/**
 * Dashboard Theme Presets
 * Each preset defines CSS variable values that get injected on <html>
 * These variables are consumed by dashboard components via inline styles or Tailwind arbitrary values
 */

const themePresets = {
    default: {
        id: 'default',
        name: 'Default',
        description: 'Clean and minimal',
        preview: {
            bg: '#ffffff',
            sidebar: '#ffffff',
            accent: '#15803d',
            card: '#ffffff',
        },
        vars: {
            '--theme-bg': '#ffffff',
            '--theme-bg-alt': '#f9fafb',
            '--theme-sidebar': '#ffffff',
            '--theme-sidebar-hover': '#f3f4f6',
            '--theme-sidebar-active': '#f0fdf4',
            '--theme-sidebar-active-text': '#15803d',
            '--theme-sidebar-text': '#6b7280',
            '--theme-accent': '#15803d',
            '--theme-accent-light': '#22c55e',
            '--theme-accent-hover': '#166534',
            '--theme-accent-surface': '#f0fdf4',
            '--theme-accent-surface-border': '#bbf7d0',
            '--theme-text': '#111827',
            '--theme-text-secondary': '#6b7280',
            '--theme-text-muted': '#9ca3af',
            '--theme-card': '#ffffff',
            '--theme-card-border': '#f0f0f0',
            '--theme-card-hover': '#fafafa',
            '--theme-border': '#f0f0f0',
            '--theme-input-bg': '#f9fafb',
            '--theme-navbar': '#ffffff',
            '--theme-navbar-border': '#f0f0f0',
            '--theme-toggle-bg': '#e5e7eb',
            '--theme-toggle-active': '#15803d',
        },
    },

    midnight: {
        id: 'midnight',
        name: 'Midnight',
        description: 'Deep dark with indigo accents',
        preview: {
            bg: '#0f172a',
            sidebar: '#1e293b',
            accent: '#818cf8',
            card: '#1e293b',
        },
        vars: {
            '--theme-bg': '#0f172a',
            '--theme-bg-alt': '#1e293b',
            '--theme-sidebar': '#1e293b',
            '--theme-sidebar-hover': '#334155',
            '--theme-sidebar-active': 'rgba(129, 140, 248, 0.1)',
            '--theme-sidebar-active-text': '#818cf8',
            '--theme-sidebar-text': '#94a3b8',
            '--theme-accent': '#818cf8',
            '--theme-accent-light': '#a5b4fc',
            '--theme-accent-hover': '#6366f1',
            '--theme-accent-surface': 'rgba(129, 140, 248, 0.1)',
            '--theme-accent-surface-border': 'rgba(129, 140, 248, 0.2)',
            '--theme-text': '#f1f5f9',
            '--theme-text-secondary': '#94a3b8',
            '--theme-text-muted': '#64748b',
            '--theme-card': '#1e293b',
            '--theme-card-border': '#334155',
            '--theme-card-hover': '#334155',
            '--theme-border': '#334155',
            '--theme-input-bg': '#0f172a',
            '--theme-navbar': '#1e293b',
            '--theme-navbar-border': '#334155',
            '--theme-toggle-bg': '#334155',
            '--theme-toggle-active': '#818cf8',
        },
    },

    ocean: {
        id: 'ocean',
        name: 'Ocean',
        description: 'Cool blues, bright and airy',
        preview: {
            bg: '#f0f9ff',
            sidebar: '#ffffff',
            accent: '#0284c7',
            card: '#ffffff',
        },
        vars: {
            '--theme-bg': '#f0f9ff',
            '--theme-bg-alt': '#e0f2fe',
            '--theme-sidebar': '#ffffff',
            '--theme-sidebar-hover': '#f0f9ff',
            '--theme-sidebar-active': '#e0f2fe',
            '--theme-sidebar-active-text': '#0284c7',
            '--theme-sidebar-text': '#64748b',
            '--theme-accent': '#0284c7',
            '--theme-accent-light': '#38bdf8',
            '--theme-accent-hover': '#0369a1',
            '--theme-accent-surface': '#e0f2fe',
            '--theme-accent-surface-border': '#bae6fd',
            '--theme-text': '#0c4a6e',
            '--theme-text-secondary': '#475569',
            '--theme-text-muted': '#94a3b8',
            '--theme-card': '#ffffff',
            '--theme-card-border': '#e0f2fe',
            '--theme-card-hover': '#f0f9ff',
            '--theme-border': '#e0f2fe',
            '--theme-input-bg': '#f0f9ff',
            '--theme-navbar': '#ffffff',
            '--theme-navbar-border': '#e0f2fe',
            '--theme-toggle-bg': '#cbd5e1',
            '--theme-toggle-active': '#0284c7',
        },
    },

    sunset: {
        id: 'sunset',
        name: 'Sunset',
        description: 'Warm dark with rose accents',
        preview: {
            bg: '#1a1a2e',
            sidebar: '#16213e',
            accent: '#e94560',
            card: '#16213e',
        },
        vars: {
            '--theme-bg': '#1a1a2e',
            '--theme-bg-alt': '#16213e',
            '--theme-sidebar': '#16213e',
            '--theme-sidebar-hover': '#1a2744',
            '--theme-sidebar-active': 'rgba(233, 69, 96, 0.1)',
            '--theme-sidebar-active-text': '#e94560',
            '--theme-sidebar-text': '#94a3b8',
            '--theme-accent': '#e94560',
            '--theme-accent-light': '#f472b6',
            '--theme-accent-hover': '#be123c',
            '--theme-accent-surface': 'rgba(233, 69, 96, 0.1)',
            '--theme-accent-surface-border': 'rgba(233, 69, 96, 0.2)',
            '--theme-text': '#eaeaea',
            '--theme-text-secondary': '#94a3b8',
            '--theme-text-muted': '#64748b',
            '--theme-card': '#16213e',
            '--theme-card-border': '#1e2d4a',
            '--theme-card-hover': '#1e2d4a',
            '--theme-border': '#1e2d4a',
            '--theme-input-bg': '#1a1a2e',
            '--theme-navbar': '#16213e',
            '--theme-navbar-border': '#1e2d4a',
            '--theme-toggle-bg': '#334155',
            '--theme-toggle-active': '#e94560',
        },
    },

    forest: {
        id: 'forest',
        name: 'Forest',
        description: 'Lush greens, natural tones',
        preview: {
            bg: '#f0fdf4',
            sidebar: '#ffffff',
            accent: '#166534',
            card: '#ffffff',
        },
        vars: {
            '--theme-bg': '#f0fdf4',
            '--theme-bg-alt': '#dcfce7',
            '--theme-sidebar': '#ffffff',
            '--theme-sidebar-hover': '#f0fdf4',
            '--theme-sidebar-active': '#dcfce7',
            '--theme-sidebar-active-text': '#166534',
            '--theme-sidebar-text': '#6b7280',
            '--theme-accent': '#166534',
            '--theme-accent-light': '#16a34a',
            '--theme-accent-hover': '#14532d',
            '--theme-accent-surface': '#dcfce7',
            '--theme-accent-surface-border': '#bbf7d0',
            '--theme-text': '#14532d',
            '--theme-text-secondary': '#374151',
            '--theme-text-muted': '#6b7280',
            '--theme-card': '#ffffff',
            '--theme-card-border': '#dcfce7',
            '--theme-card-hover': '#f0fdf4',
            '--theme-border': '#dcfce7',
            '--theme-input-bg': '#f0fdf4',
            '--theme-navbar': '#ffffff',
            '--theme-navbar-border': '#dcfce7',
            '--theme-toggle-bg': '#d1d5db',
            '--theme-toggle-active': '#166534',
        },
    },
};

export default themePresets;
