/**
 * Mobile Theme Presets
 * Each preset defines color values consumed by React Native StyleSheet.
 * Mirrors the webapp's themePresets.js but uses direct color objects
 * instead of CSS custom properties.
 */

const themePresets = {
    default: {
        id: 'default',
        name: 'Default',
        description: 'Clean and minimal',
        preview: {
            bg: '#ffffff',
            sidebar: '#ffffff',
            accent: '#15803d',
            card: '#ffffff',
        },
        colors: {
            bg: '#f4f4f5',
            bgAlt: '#f9fafb',
            card: '#ffffff',
            cardBorder: '#f0f0f0',
            cardHover: '#fafafa',
            accent: '#10b981',
            accentDark: '#15803d',
            accentLight: '#22c55e',
            accentSurface: '#f0fdf4',
            accentSurfaceBorder: '#bbf7d0',
            text: '#18181b',
            textSecondary: '#a1a1aa',
            textMuted: '#d4d4d8',
            border: '#f0f0f0',
            inputBg: '#f9fafb',
            tabBar: '#ffffff',
            tabBarBorder: '#e5e7eb',
            tabBarActive: '#10b981',
            tabBarInactive: '#c4c4c6',
            switchTrackOff: '#cbd5e1',
            switchTrackOn: '#a7f3d0',
            switchThumbOn: '#10b981',
            switchThumbOff: '#f8fafc',
            header: '#ffffff',
            skeleton: '#e4e4e7',
            danger: '#ef4444',
            dangerBg: '#fef2f2',
            dangerBorder: '#fecaca',
            modalOverlay: 'rgba(0,0,0,0.3)',
            modalBg: '#ffffff',
        },
    },

    midnight: {
        id: 'midnight',
        name: 'Midnight',
        description: 'Deep dark with indigo accents',
        preview: {
            bg: '#0f172a',
            sidebar: '#1e293b',
            accent: '#818cf8',
            card: '#1e293b',
        },
        colors: {
            bg: '#0f172a',
            bgAlt: '#1e293b',
            card: '#1e293b',
            cardBorder: '#334155',
            cardHover: '#334155',
            accent: '#818cf8',
            accentDark: '#6366f1',
            accentLight: '#a5b4fc',
            accentSurface: 'rgba(129, 140, 248, 0.1)',
            accentSurfaceBorder: 'rgba(129, 140, 248, 0.2)',
            text: '#f1f5f9',
            textSecondary: '#94a3b8',
            textMuted: '#64748b',
            border: '#334155',
            inputBg: '#0f172a',
            tabBar: '#1e293b',
            tabBarBorder: '#334155',
            tabBarActive: '#818cf8',
            tabBarInactive: '#64748b',
            switchTrackOff: '#334155',
            switchTrackOn: 'rgba(129, 140, 248, 0.4)',
            switchThumbOn: '#818cf8',
            switchThumbOff: '#94a3b8',
            header: '#1e293b',
            skeleton: '#334155',
            danger: '#f87171',
            dangerBg: 'rgba(239, 68, 68, 0.1)',
            dangerBorder: 'rgba(239, 68, 68, 0.2)',
            modalOverlay: 'rgba(0,0,0,0.6)',
            modalBg: '#1e293b',
        },
    },

    ocean: {
        id: 'ocean',
        name: 'Ocean',
        description: 'Cool blues, bright and airy',
        preview: {
            bg: '#f0f9ff',
            sidebar: '#ffffff',
            accent: '#0284c7',
            card: '#ffffff',
        },
        colors: {
            bg: '#f0f9ff',
            bgAlt: '#e0f2fe',
            card: '#ffffff',
            cardBorder: '#e0f2fe',
            cardHover: '#f0f9ff',
            accent: '#0284c7',
            accentDark: '#0369a1',
            accentLight: '#38bdf8',
            accentSurface: '#e0f2fe',
            accentSurfaceBorder: '#bae6fd',
            text: '#0c4a6e',
            textSecondary: '#475569',
            textMuted: '#94a3b8',
            border: '#e0f2fe',
            inputBg: '#f0f9ff',
            tabBar: '#ffffff',
            tabBarBorder: '#e0f2fe',
            tabBarActive: '#0284c7',
            tabBarInactive: '#94a3b8',
            switchTrackOff: '#cbd5e1',
            switchTrackOn: '#bae6fd',
            switchThumbOn: '#0284c7',
            switchThumbOff: '#f8fafc',
            header: '#ffffff',
            skeleton: '#e0f2fe',
            danger: '#ef4444',
            dangerBg: '#fef2f2',
            dangerBorder: '#fecaca',
            modalOverlay: 'rgba(0,0,0,0.3)',
            modalBg: '#ffffff',
        },
    },

    sunset: {
        id: 'sunset',
        name: 'Sunset',
        description: 'Warm dark with rose accents',
        preview: {
            bg: '#1a1a2e',
            sidebar: '#16213e',
            accent: '#e94560',
            card: '#16213e',
        },
        colors: {
            bg: '#1a1a2e',
            bgAlt: '#16213e',
            card: '#16213e',
            cardBorder: '#1e2d4a',
            cardHover: '#1e2d4a',
            accent: '#e94560',
            accentDark: '#be123c',
            accentLight: '#f472b6',
            accentSurface: 'rgba(233, 69, 96, 0.1)',
            accentSurfaceBorder: 'rgba(233, 69, 96, 0.2)',
            text: '#eaeaea',
            textSecondary: '#94a3b8',
            textMuted: '#64748b',
            border: '#1e2d4a',
            inputBg: '#1a1a2e',
            tabBar: '#16213e',
            tabBarBorder: '#1e2d4a',
            tabBarActive: '#e94560',
            tabBarInactive: '#64748b',
            switchTrackOff: '#334155',
            switchTrackOn: 'rgba(233, 69, 96, 0.4)',
            switchThumbOn: '#e94560',
            switchThumbOff: '#94a3b8',
            header: '#16213e',
            skeleton: '#1e2d4a',
            danger: '#f87171',
            dangerBg: 'rgba(239, 68, 68, 0.1)',
            dangerBorder: 'rgba(239, 68, 68, 0.2)',
            modalOverlay: 'rgba(0,0,0,0.6)',
            modalBg: '#16213e',
        },
    },

    forest: {
        id: 'forest',
        name: 'Forest',
        description: 'Lush greens, natural tones',
        preview: {
            bg: '#f0fdf4',
            sidebar: '#ffffff',
            accent: '#166534',
            card: '#ffffff',
        },
        colors: {
            bg: '#f0fdf4',
            bgAlt: '#dcfce7',
            card: '#ffffff',
            cardBorder: '#dcfce7',
            cardHover: '#f0fdf4',
            accent: '#16a34a',
            accentDark: '#166534',
            accentLight: '#16a34a',
            accentSurface: '#dcfce7',
            accentSurfaceBorder: '#bbf7d0',
            text: '#14532d',
            textSecondary: '#374151',
            textMuted: '#6b7280',
            border: '#dcfce7',
            inputBg: '#f0fdf4',
            tabBar: '#ffffff',
            tabBarBorder: '#dcfce7',
            tabBarActive: '#166534',
            tabBarInactive: '#6b7280',
            switchTrackOff: '#d1d5db',
            switchTrackOn: '#bbf7d0',
            switchThumbOn: '#166534',
            switchThumbOff: '#f8fafc',
            header: '#ffffff',
            skeleton: '#dcfce7',
            danger: '#ef4444',
            dangerBg: '#fef2f2',
            dangerBorder: '#fecaca',
            modalOverlay: 'rgba(0,0,0,0.3)',
            modalBg: '#ffffff',
        },
    },
};

export default themePresets;
